"""files.is_image

Revision ID: 0df05d29c390
Revises: 2fc646ff2283
Create Date: 2026-09-09 17:55:36.764682
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0df05d29c390'
down_revision: Union[str, None] = '2fc646ff2283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_image', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_image')
    # ### end Alembic commands ###
